version: '3.7'

services:

  dst:
    image: "alhimikix/steamcmd-dst"
    entrypoint: "./runserver.sh"
    restart: "unless-stopped"
    volumes:
      - game:/root/dontstarvetogether_dedicated_server
      - ./DoNotStarveTogether:/root/.klei/DoNotStarveTogether
      - ./mods:/root/dontstarvetogether_dedicated_server/mods


volumes:
  game:

